### ISSUE TITLE
[Android]Error: There's a problem with this sticker pack and it can't be added to WhatsApp 

### ISSUE THREAD

**Issue by sidoruvigo** [viztushar/flutter_whatsapp_stickers_internet#2]
I have downloaded the app and everything looks great, however, after installing and desinstalling the stickers pack, I'm getting: "There's a problem with this sticker pack and it can't be added to WhatsApp", and there is no way to make it run properly again. I did flutter clean, I've installed the app again but the issue persists. Running on LG H815.

**Comment by sidoruvigo** [comment]
After some research, I could add the stickers to whatsapp, however, after  desinstalling the stickers pack several times I'm having the issue again. Maybe related to [this issue](https://github.com/WhatsApp/stickers/issues/584).

**Comment by grayknight2** [comment]
An update is needed in order to incorporate `avoid_cache` and `image_data_version` fields in the stickers json and the models as discussed [here](https://github.com/vincekruger/flutter_whatsapp_stickers/issues/1).

**Comment by viztushar** [comment]
fix this issues in [4d3f294](https://github.com/viztushar/flutter_whatsapp_stickers_internet/commit/4d3f294df431cedd5ff1c22abcec4cd0950548c1) 

closing this issue. if there is any issues feel free to reopen the issue
